# Generated by Django 4.2 on 2024-02-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_documentmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="motivation_document",
            field=models.FileField(blank=True, upload_to="motivation-documents"),
        ),
    ]
