# Generated by Django 4.2 on 2024-02-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_document_motivation_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentmatch",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
