# Generated by Django 4.2 on 2024-02-21 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(verbose_name='Detail')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.review', verbose_name='Review')),
            ],
        ),
    ]
