# Generated by Django 4.2 on 2024-02-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5, verbose_name='Rating (1-5)'),
            preserve_default=False,
        ),
    ]
